import sys

with open('CMakeLists.txt', 'r') as f:
    lines = f.readlines()

start_idx = -1
end_idx = -1
for i, line in enumerate(lines):
    if '# Macros' in line and i > 300 and i < 400:
        start_idx = i
        # Keep searching for the LAST marker in that range to avoid double blocks
    if 'set(CBF__SRC' in line and i > 450 and i < 600:
        end_idx = i
        break

if start_idx != -1 and end_idx != -1:
    new_content = lines[:start_idx]
    new_content.append("#\n# Macros\n#\n\n")
    new_content.append("macro(CBF_DEBUG_MESSAGE str)\n")
    new_content.append("  if(CBF_CMAKE_DEBUG)\n")
    new_content.append("    message(STATUS ${str})\n")
    new_content.append("  endif(CBF_CMAKE_DEBUG)\n")
    new_content.append("endmacro (CBF_DEBUG_MESSAGE)\n\n")
    new_content.append("macro(CBF_REQUIRE_DIRECTORY dir)\n")
    new_content.append("  if (NOT EXISTS \"${dir}\")\n")
    new_content.append("    file(MAKE_DIRECTORY \"${dir}\")\n")
    new_content.append("    CBF_DEBUG_MESSAGE(\"Created directory ${dir}\")\n")
    new_content.append("  endif (NOT EXISTS \"${dir}\")\n")
    new_content.append("endmacro(CBF_REQUIRE_DIRECTORY)\n\n")
    new_content.append("macro(CBF_AUTO_INSTALL_DEPENDENCY FIND_NAME VCPKG_NAME PORT_NAME APT_NAME CONDITION)\n")
    new_content.append("  if(${CONDITION})\n")
    new_content.append("    set(_FOUND FALSE)\n")
    new_content.append("    if(\"${FIND_NAME}\" STREQUAL \"zstd\" AND WIN32)\n")
    new_content.append("      # On Windows, check for zstd.h to avoid target pollution that conflicts with LibTIFF\n")
    new_content.append("      find_path(ZSTD_CHECK_INCLUDE NAMES zstd.h QUIET)\n")
    new_content.append("      if(ZSTD_CHECK_INCLUDE)\n")
    new_content.append("        set(_FOUND TRUE)\n")
    new_content.append("      endif()\n")
    new_content.append("    else()\n")
    new_content.append("      find_package(${FIND_NAME} QUIET)\n")
    new_content.append("      if(${FIND_NAME}_FOUND OR ${FIND_NAME}_Found OR ${${FIND_NAME}_FOUND})\n")
    new_content.append("        set(_FOUND TRUE)\n")
    new_content.append("      endif()\n")
    new_content.append("    endif()\n\n")
    new_content.append("    if(NOT _FOUND)\n")
    new_content.append("      find_package(PkgConfig QUIET)\n")
    new_content.append("      if(PKG_CONFIG_FOUND)\n")
    new_content.append("        pkg_check_modules(CBF_AUTO_${FIND_NAME} QUIET ${FIND_NAME})\n")
    new_content.append("        if(CBF_AUTO_${FIND_NAME}_FOUND)\n")
    new_content.append("          set(_FOUND TRUE)\n")
    new_content.append("        endif()\n")
    new_content.append("      endif()\n")
    new_content.append("    endif()\n\n")
    new_content.append("    if(NOT _FOUND)\n")
    new_content.append("      message(STATUS \"Dependency ${FIND_NAME} not found. Attempting to install...\")\n")
    new_content.append("      set(_install_res 1)\n")
    new_content.append("      if(WIN32)\n")
    new_content.append("        if(NOT \"${VCPKG_NAME}\" STREQUAL \"SKIP\")\n")
    new_content.append("          execute_process(COMMAND vcpkg install ${VCPKG_NAME} RESULT_VARIABLE _install_res)\n")
    new_content.append("        endif()\n")
    new_content.append("      elif(APPLE)\n")
    new_content.append("        if(NOT \"${PORT_NAME}\" STREQUAL \"SKIP\")\n")
    new_content.append("          execute_process(COMMAND sudo port install ${PORT_NAME} RESULT_VARIABLE _install_res)\n")
    new_content.append("        endif()\n")
    new_content.append("      elif(UNIX AND NOT APPLE)\n")
    new_content.append("        if(NOT \"${APT_NAME}\" STREQUAL \"SKIP\")\n")
    new_content.append("          execute_process(COMMAND sudo apt-get install -y ${APT_NAME} RESULT_VARIABLE _install_res)\n")
    new_content.append("        endif()\n")
    new_content.append("      endif()\n")
    new_content.append("      if(_install_res EQUAL 0)\n")
    new_content.append("        message(STATUS \"Successfully installed ${FIND_NAME}. Retrying find_package...\")\n")
    new_content.append("        find_package(${FIND_NAME} QUIET)\n")
    new_content.append("      else()\n")
    new_content.append("        if(NOT _FOUND)\n")
    new_content.append("          message(WARNING \"Failed to install ${FIND_NAME} (or installation skipped).\")\n")
    new_content.append("        endif()\n")
    new_content.append("      endif()\n")
    new_content.append("    endif()\n")
    new_content.append("  endif()\n")
    new_content.append("endmacro()\n\n")
    new_content.append("set(NOT_CBF_WITH_LIBTIFF NOT CBF_WITH_LIBTIFF)\n")
    new_content.append("set(NOT_CBF_WITH_PCRE2 NOT CBF_WITH_PCRE2)\n")
    new_content.append("set(NOT_CBF_WITH_HDF5 NOT CBF_WITH_HDF5)\n\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(BZip2 bzip2 bzip2 libbz2-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(libdeflate libdeflate libdeflate libdeflate-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(JPEG libjpeg-turbo libjpeg-turbo libjpeg-turbo8-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(JBIG jbigkit jbigkit libjbig-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(LERC lerc lerc liblerc-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(LibLZMA liblzma xz liblzma-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(zstd zstd zstd libzstd-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(WebP libwebp webp libwebp-dev NOT_CBF_WITH_LIBTIFF)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(GLUT freeglut freeglut freeglut3-dev TRUE)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(Editline SKIP libedit libedit-dev TRUE)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(PCRE2 pcre2 pcre2 libpcre2-dev NOT_CBF_WITH_PCRE2)\n")
    new_content.append("CBF_AUTO_INSTALL_DEPENDENCY(HDF5 hdf5 hdf5 libhdf5-dev NOT_CBF_WITH_HDF5)\n\n")
    new_content.extend(lines[end_idx:])

    with open('CMakeLists.txt', 'w') as f:
        f.writelines(new_content)
    print("Successfully fixed CMakeLists.txt")
else:
    print(f"Failed to find markers: start_idx={start_idx}, end_idx={end_idx}")
