macro(patch_file FILE_PATH SEARCH REPLACE)
  if(EXISTS "${FILE_PATH}")
    file(READ "${FILE_PATH}" content)
    string(REPLACE "${SEARCH}" "${REPLACE}" content "${content}")
    file(WRITE "${FILE_PATH}" "${content}")
  endif()
endmacro()

patch_file("${hdf5_SOURCE_DIR}/config/cmake/ZLIB/CMakeLists.txt" " STATIC " " SHARED ")
patch_file("${hdf5_SOURCE_DIR}/config/cmake/ZLIB/CMakeLists.txt" "zlib-static" "zlib")
patch_file("${hdf5_SOURCE_DIR}/config/cmake/LIBAEC/CMakeLists.txt" " STATIC " " SHARED ")
patch_file("${hdf5_SOURCE_DIR}/config/cmake/LIBAEC/CMakeLists.txt" "-static" "")
patch_file("${hdf5_SOURCE_DIR}/config/cmake/HDFLibMacros.cmake" "STATIC" "SHARED")
patch_file("${hdf5_SOURCE_DIR}/config/cmake/HDFLibMacros.cmake" "-static" "")
